//separate routes will use separate layout

import Footer from "../_ui/Footer";

import "../global.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="my-16">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
