import "./global.css";
export const metadata = {
  title: {
    default: "Auth",
    template: "Auth | %s",
  },
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
