import Footer from "../_ui/Footer";
import Header from "../_ui/Header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <main className="my-16">{children}</main>
      <Footer />
    </>
  );
}
